/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.impala.extdatasource.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)")
public class TCloseParams implements org.apache.thrift.TBase<TCloseParams, TCloseParams._Fields>, java.io.Serializable, Cloneable, Comparable<TCloseParams> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TCloseParams");

  private static final org.apache.thrift.protocol.TField SCAN_HANDLE_FIELD_DESC = new org.apache.thrift.protocol.TField("scan_handle", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TCloseParamsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TCloseParamsTupleSchemeFactory());
  }

  private String scan_handle; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SCAN_HANDLE((short)1, "scan_handle");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SCAN_HANDLE
          return SCAN_HANDLE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.SCAN_HANDLE};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SCAN_HANDLE, new org.apache.thrift.meta_data.FieldMetaData("scan_handle", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TCloseParams.class, metaDataMap);
  }

  public TCloseParams() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TCloseParams(TCloseParams other) {
    if (other.isSetScan_handle()) {
      this.scan_handle = other.scan_handle;
    }
  }

  public TCloseParams deepCopy() {
    return new TCloseParams(this);
  }

  @Override
  public void clear() {
    this.scan_handle = null;
  }

  public String getScan_handle() {
    return this.scan_handle;
  }

  public void setScan_handle(String scan_handle) {
    this.scan_handle = scan_handle;
  }

  public void unsetScan_handle() {
    this.scan_handle = null;
  }

  /** Returns true if field scan_handle is set (has been assigned a value) and false otherwise */
  public boolean isSetScan_handle() {
    return this.scan_handle != null;
  }

  public void setScan_handleIsSet(boolean value) {
    if (!value) {
      this.scan_handle = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SCAN_HANDLE:
      if (value == null) {
        unsetScan_handle();
      } else {
        setScan_handle((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SCAN_HANDLE:
      return getScan_handle();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SCAN_HANDLE:
      return isSetScan_handle();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TCloseParams)
      return this.equals((TCloseParams)that);
    return false;
  }

  public boolean equals(TCloseParams that) {
    if (that == null)
      return false;

    boolean this_present_scan_handle = true && this.isSetScan_handle();
    boolean that_present_scan_handle = true && that.isSetScan_handle();
    if (this_present_scan_handle || that_present_scan_handle) {
      if (!(this_present_scan_handle && that_present_scan_handle))
        return false;
      if (!this.scan_handle.equals(that.scan_handle))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_scan_handle = true && (isSetScan_handle());
    list.add(present_scan_handle);
    if (present_scan_handle)
      list.add(scan_handle);

    return list.hashCode();
  }

  @Override
  public int compareTo(TCloseParams other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetScan_handle()).compareTo(other.isSetScan_handle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetScan_handle()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.scan_handle, other.scan_handle);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TCloseParams(");
    boolean first = true;

    if (isSetScan_handle()) {
      sb.append("scan_handle:");
      if (this.scan_handle == null) {
        sb.append("null");
      } else {
        sb.append(this.scan_handle);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TCloseParamsStandardSchemeFactory implements SchemeFactory {
    public TCloseParamsStandardScheme getScheme() {
      return new TCloseParamsStandardScheme();
    }
  }

  private static class TCloseParamsStandardScheme extends StandardScheme<TCloseParams> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TCloseParams struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SCAN_HANDLE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.scan_handle = iprot.readString();
              struct.setScan_handleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TCloseParams struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.scan_handle != null) {
        if (struct.isSetScan_handle()) {
          oprot.writeFieldBegin(SCAN_HANDLE_FIELD_DESC);
          oprot.writeString(struct.scan_handle);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TCloseParamsTupleSchemeFactory implements SchemeFactory {
    public TCloseParamsTupleScheme getScheme() {
      return new TCloseParamsTupleScheme();
    }
  }

  private static class TCloseParamsTupleScheme extends TupleScheme<TCloseParams> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TCloseParams struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetScan_handle()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetScan_handle()) {
        oprot.writeString(struct.scan_handle);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TCloseParams struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.scan_handle = iprot.readString();
        struct.setScan_handleIsSet(true);
      }
    }
  }

}

