/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.impala.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2019-11-08")
public class TEqJoinCondition implements org.apache.thrift.TBase<TEqJoinCondition, TEqJoinCondition._Fields>, java.io.Serializable, Cloneable, Comparable<TEqJoinCondition> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TEqJoinCondition");

  private static final org.apache.thrift.protocol.TField LEFT_FIELD_DESC = new org.apache.thrift.protocol.TField("left", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField RIGHT_FIELD_DESC = new org.apache.thrift.protocol.TField("right", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField IS_NOT_DISTINCT_FROM_FIELD_DESC = new org.apache.thrift.protocol.TField("is_not_distinct_from", org.apache.thrift.protocol.TType.BOOL, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TEqJoinConditionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TEqJoinConditionTupleSchemeFactory());
  }

  public org.apache.impala.thrift.TExpr left; // required
  public org.apache.impala.thrift.TExpr right; // required
  public boolean is_not_distinct_from; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LEFT((short)1, "left"),
    RIGHT((short)2, "right"),
    IS_NOT_DISTINCT_FROM((short)3, "is_not_distinct_from");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LEFT
          return LEFT;
        case 2: // RIGHT
          return RIGHT;
        case 3: // IS_NOT_DISTINCT_FROM
          return IS_NOT_DISTINCT_FROM;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __IS_NOT_DISTINCT_FROM_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LEFT, new org.apache.thrift.meta_data.FieldMetaData("left", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, org.apache.impala.thrift.TExpr.class)));
    tmpMap.put(_Fields.RIGHT, new org.apache.thrift.meta_data.FieldMetaData("right", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, org.apache.impala.thrift.TExpr.class)));
    tmpMap.put(_Fields.IS_NOT_DISTINCT_FROM, new org.apache.thrift.meta_data.FieldMetaData("is_not_distinct_from", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TEqJoinCondition.class, metaDataMap);
  }

  public TEqJoinCondition() {
  }

  public TEqJoinCondition(
    org.apache.impala.thrift.TExpr left,
    org.apache.impala.thrift.TExpr right,
    boolean is_not_distinct_from)
  {
    this();
    this.left = left;
    this.right = right;
    this.is_not_distinct_from = is_not_distinct_from;
    setIs_not_distinct_fromIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TEqJoinCondition(TEqJoinCondition other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetLeft()) {
      this.left = new org.apache.impala.thrift.TExpr(other.left);
    }
    if (other.isSetRight()) {
      this.right = new org.apache.impala.thrift.TExpr(other.right);
    }
    this.is_not_distinct_from = other.is_not_distinct_from;
  }

  public TEqJoinCondition deepCopy() {
    return new TEqJoinCondition(this);
  }

  @Override
  public void clear() {
    this.left = null;
    this.right = null;
    setIs_not_distinct_fromIsSet(false);
    this.is_not_distinct_from = false;
  }

  public org.apache.impala.thrift.TExpr getLeft() {
    return this.left;
  }

  public TEqJoinCondition setLeft(org.apache.impala.thrift.TExpr left) {
    this.left = left;
    return this;
  }

  public void unsetLeft() {
    this.left = null;
  }

  /** Returns true if field left is set (has been assigned a value) and false otherwise */
  public boolean isSetLeft() {
    return this.left != null;
  }

  public void setLeftIsSet(boolean value) {
    if (!value) {
      this.left = null;
    }
  }

  public org.apache.impala.thrift.TExpr getRight() {
    return this.right;
  }

  public TEqJoinCondition setRight(org.apache.impala.thrift.TExpr right) {
    this.right = right;
    return this;
  }

  public void unsetRight() {
    this.right = null;
  }

  /** Returns true if field right is set (has been assigned a value) and false otherwise */
  public boolean isSetRight() {
    return this.right != null;
  }

  public void setRightIsSet(boolean value) {
    if (!value) {
      this.right = null;
    }
  }

  public boolean isIs_not_distinct_from() {
    return this.is_not_distinct_from;
  }

  public TEqJoinCondition setIs_not_distinct_from(boolean is_not_distinct_from) {
    this.is_not_distinct_from = is_not_distinct_from;
    setIs_not_distinct_fromIsSet(true);
    return this;
  }

  public void unsetIs_not_distinct_from() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __IS_NOT_DISTINCT_FROM_ISSET_ID);
  }

  /** Returns true if field is_not_distinct_from is set (has been assigned a value) and false otherwise */
  public boolean isSetIs_not_distinct_from() {
    return EncodingUtils.testBit(__isset_bitfield, __IS_NOT_DISTINCT_FROM_ISSET_ID);
  }

  public void setIs_not_distinct_fromIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __IS_NOT_DISTINCT_FROM_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case LEFT:
      if (value == null) {
        unsetLeft();
      } else {
        setLeft((org.apache.impala.thrift.TExpr)value);
      }
      break;

    case RIGHT:
      if (value == null) {
        unsetRight();
      } else {
        setRight((org.apache.impala.thrift.TExpr)value);
      }
      break;

    case IS_NOT_DISTINCT_FROM:
      if (value == null) {
        unsetIs_not_distinct_from();
      } else {
        setIs_not_distinct_from((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case LEFT:
      return getLeft();

    case RIGHT:
      return getRight();

    case IS_NOT_DISTINCT_FROM:
      return isIs_not_distinct_from();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case LEFT:
      return isSetLeft();
    case RIGHT:
      return isSetRight();
    case IS_NOT_DISTINCT_FROM:
      return isSetIs_not_distinct_from();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TEqJoinCondition)
      return this.equals((TEqJoinCondition)that);
    return false;
  }

  public boolean equals(TEqJoinCondition that) {
    if (that == null)
      return false;

    boolean this_present_left = true && this.isSetLeft();
    boolean that_present_left = true && that.isSetLeft();
    if (this_present_left || that_present_left) {
      if (!(this_present_left && that_present_left))
        return false;
      if (!this.left.equals(that.left))
        return false;
    }

    boolean this_present_right = true && this.isSetRight();
    boolean that_present_right = true && that.isSetRight();
    if (this_present_right || that_present_right) {
      if (!(this_present_right && that_present_right))
        return false;
      if (!this.right.equals(that.right))
        return false;
    }

    boolean this_present_is_not_distinct_from = true;
    boolean that_present_is_not_distinct_from = true;
    if (this_present_is_not_distinct_from || that_present_is_not_distinct_from) {
      if (!(this_present_is_not_distinct_from && that_present_is_not_distinct_from))
        return false;
      if (this.is_not_distinct_from != that.is_not_distinct_from)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_left = true && (isSetLeft());
    list.add(present_left);
    if (present_left)
      list.add(left);

    boolean present_right = true && (isSetRight());
    list.add(present_right);
    if (present_right)
      list.add(right);

    boolean present_is_not_distinct_from = true;
    list.add(present_is_not_distinct_from);
    if (present_is_not_distinct_from)
      list.add(is_not_distinct_from);

    return list.hashCode();
  }

  @Override
  public int compareTo(TEqJoinCondition other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetLeft()).compareTo(other.isSetLeft());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLeft()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.left, other.left);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRight()).compareTo(other.isSetRight());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRight()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.right, other.right);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIs_not_distinct_from()).compareTo(other.isSetIs_not_distinct_from());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIs_not_distinct_from()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.is_not_distinct_from, other.is_not_distinct_from);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TEqJoinCondition(");
    boolean first = true;

    sb.append("left:");
    if (this.left == null) {
      sb.append("null");
    } else {
      sb.append(this.left);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("right:");
    if (this.right == null) {
      sb.append("null");
    } else {
      sb.append(this.right);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("is_not_distinct_from:");
    sb.append(this.is_not_distinct_from);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (left == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'left' was not present! Struct: " + toString());
    }
    if (right == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'right' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'is_not_distinct_from' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
    if (left != null) {
      left.validate();
    }
    if (right != null) {
      right.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TEqJoinConditionStandardSchemeFactory implements SchemeFactory {
    public TEqJoinConditionStandardScheme getScheme() {
      return new TEqJoinConditionStandardScheme();
    }
  }

  private static class TEqJoinConditionStandardScheme extends StandardScheme<TEqJoinCondition> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TEqJoinCondition struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LEFT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.left = new org.apache.impala.thrift.TExpr();
              struct.left.read(iprot);
              struct.setLeftIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RIGHT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.right = new org.apache.impala.thrift.TExpr();
              struct.right.read(iprot);
              struct.setRightIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // IS_NOT_DISTINCT_FROM
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.is_not_distinct_from = iprot.readBool();
              struct.setIs_not_distinct_fromIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetIs_not_distinct_from()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'is_not_distinct_from' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TEqJoinCondition struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.left != null) {
        oprot.writeFieldBegin(LEFT_FIELD_DESC);
        struct.left.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.right != null) {
        oprot.writeFieldBegin(RIGHT_FIELD_DESC);
        struct.right.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(IS_NOT_DISTINCT_FROM_FIELD_DESC);
      oprot.writeBool(struct.is_not_distinct_from);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TEqJoinConditionTupleSchemeFactory implements SchemeFactory {
    public TEqJoinConditionTupleScheme getScheme() {
      return new TEqJoinConditionTupleScheme();
    }
  }

  private static class TEqJoinConditionTupleScheme extends TupleScheme<TEqJoinCondition> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TEqJoinCondition struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.left.write(oprot);
      struct.right.write(oprot);
      oprot.writeBool(struct.is_not_distinct_from);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TEqJoinCondition struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.left = new org.apache.impala.thrift.TExpr();
      struct.left.read(iprot);
      struct.setLeftIsSet(true);
      struct.right = new org.apache.impala.thrift.TExpr();
      struct.right.read(iprot);
      struct.setRightIsSet(true);
      struct.is_not_distinct_from = iprot.readBool();
      struct.setIs_not_distinct_fromIsSet(true);
    }
  }

}

