/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.impala.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)")
public class TExtractFromZipParams implements org.apache.thrift.TBase<TExtractFromZipParams, TExtractFromZipParams._Fields>, java.io.Serializable, Cloneable, Comparable<TExtractFromZipParams> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TExtractFromZipParams");

  private static final org.apache.thrift.protocol.TField ARCHIVE_FILE_FIELD_DESC = new org.apache.thrift.protocol.TField("archive_file", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField DESTINATION_DIR_FIELD_DESC = new org.apache.thrift.protocol.TField("destination_dir", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TExtractFromZipParamsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TExtractFromZipParamsTupleSchemeFactory());
  }

  private String archive_file; // required
  private String destination_dir; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ARCHIVE_FILE((short)1, "archive_file"),
    DESTINATION_DIR((short)2, "destination_dir");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ARCHIVE_FILE
          return ARCHIVE_FILE;
        case 2: // DESTINATION_DIR
          return DESTINATION_DIR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ARCHIVE_FILE, new org.apache.thrift.meta_data.FieldMetaData("archive_file", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DESTINATION_DIR, new org.apache.thrift.meta_data.FieldMetaData("destination_dir", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TExtractFromZipParams.class, metaDataMap);
  }

  public TExtractFromZipParams() {
  }

  public TExtractFromZipParams(
    String archive_file,
    String destination_dir)
  {
    this();
    this.archive_file = archive_file;
    this.destination_dir = destination_dir;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TExtractFromZipParams(TExtractFromZipParams other) {
    if (other.isSetArchive_file()) {
      this.archive_file = other.archive_file;
    }
    if (other.isSetDestination_dir()) {
      this.destination_dir = other.destination_dir;
    }
  }

  public TExtractFromZipParams deepCopy() {
    return new TExtractFromZipParams(this);
  }

  @Override
  public void clear() {
    this.archive_file = null;
    this.destination_dir = null;
  }

  public String getArchive_file() {
    return this.archive_file;
  }

  public void setArchive_file(String archive_file) {
    this.archive_file = archive_file;
  }

  public void unsetArchive_file() {
    this.archive_file = null;
  }

  /** Returns true if field archive_file is set (has been assigned a value) and false otherwise */
  public boolean isSetArchive_file() {
    return this.archive_file != null;
  }

  public void setArchive_fileIsSet(boolean value) {
    if (!value) {
      this.archive_file = null;
    }
  }

  public String getDestination_dir() {
    return this.destination_dir;
  }

  public void setDestination_dir(String destination_dir) {
    this.destination_dir = destination_dir;
  }

  public void unsetDestination_dir() {
    this.destination_dir = null;
  }

  /** Returns true if field destination_dir is set (has been assigned a value) and false otherwise */
  public boolean isSetDestination_dir() {
    return this.destination_dir != null;
  }

  public void setDestination_dirIsSet(boolean value) {
    if (!value) {
      this.destination_dir = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ARCHIVE_FILE:
      if (value == null) {
        unsetArchive_file();
      } else {
        setArchive_file((String)value);
      }
      break;

    case DESTINATION_DIR:
      if (value == null) {
        unsetDestination_dir();
      } else {
        setDestination_dir((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ARCHIVE_FILE:
      return getArchive_file();

    case DESTINATION_DIR:
      return getDestination_dir();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ARCHIVE_FILE:
      return isSetArchive_file();
    case DESTINATION_DIR:
      return isSetDestination_dir();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TExtractFromZipParams)
      return this.equals((TExtractFromZipParams)that);
    return false;
  }

  public boolean equals(TExtractFromZipParams that) {
    if (that == null)
      return false;

    boolean this_present_archive_file = true && this.isSetArchive_file();
    boolean that_present_archive_file = true && that.isSetArchive_file();
    if (this_present_archive_file || that_present_archive_file) {
      if (!(this_present_archive_file && that_present_archive_file))
        return false;
      if (!this.archive_file.equals(that.archive_file))
        return false;
    }

    boolean this_present_destination_dir = true && this.isSetDestination_dir();
    boolean that_present_destination_dir = true && that.isSetDestination_dir();
    if (this_present_destination_dir || that_present_destination_dir) {
      if (!(this_present_destination_dir && that_present_destination_dir))
        return false;
      if (!this.destination_dir.equals(that.destination_dir))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_archive_file = true && (isSetArchive_file());
    list.add(present_archive_file);
    if (present_archive_file)
      list.add(archive_file);

    boolean present_destination_dir = true && (isSetDestination_dir());
    list.add(present_destination_dir);
    if (present_destination_dir)
      list.add(destination_dir);

    return list.hashCode();
  }

  @Override
  public int compareTo(TExtractFromZipParams other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetArchive_file()).compareTo(other.isSetArchive_file());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetArchive_file()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.archive_file, other.archive_file);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDestination_dir()).compareTo(other.isSetDestination_dir());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDestination_dir()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.destination_dir, other.destination_dir);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TExtractFromZipParams(");
    boolean first = true;

    sb.append("archive_file:");
    if (this.archive_file == null) {
      sb.append("null");
    } else {
      sb.append(this.archive_file);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("destination_dir:");
    if (this.destination_dir == null) {
      sb.append("null");
    } else {
      sb.append(this.destination_dir);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!isSetArchive_file()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'archive_file' is unset! Struct:" + toString());
    }

    if (!isSetDestination_dir()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'destination_dir' is unset! Struct:" + toString());
    }

    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TExtractFromZipParamsStandardSchemeFactory implements SchemeFactory {
    public TExtractFromZipParamsStandardScheme getScheme() {
      return new TExtractFromZipParamsStandardScheme();
    }
  }

  private static class TExtractFromZipParamsStandardScheme extends StandardScheme<TExtractFromZipParams> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TExtractFromZipParams struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ARCHIVE_FILE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.archive_file = iprot.readString();
              struct.setArchive_fileIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DESTINATION_DIR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.destination_dir = iprot.readString();
              struct.setDestination_dirIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TExtractFromZipParams struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.archive_file != null) {
        oprot.writeFieldBegin(ARCHIVE_FILE_FIELD_DESC);
        oprot.writeString(struct.archive_file);
        oprot.writeFieldEnd();
      }
      if (struct.destination_dir != null) {
        oprot.writeFieldBegin(DESTINATION_DIR_FIELD_DESC);
        oprot.writeString(struct.destination_dir);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TExtractFromZipParamsTupleSchemeFactory implements SchemeFactory {
    public TExtractFromZipParamsTupleScheme getScheme() {
      return new TExtractFromZipParamsTupleScheme();
    }
  }

  private static class TExtractFromZipParamsTupleScheme extends TupleScheme<TExtractFromZipParams> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TExtractFromZipParams struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.archive_file);
      oprot.writeString(struct.destination_dir);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TExtractFromZipParams struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.archive_file = iprot.readString();
      struct.setArchive_fileIsSet(true);
      struct.destination_dir = iprot.readString();
      struct.setDestination_dirIsSet(true);
    }
  }

}

