/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.impala.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2019-11-08")
public class TScanRangeLocation implements org.apache.thrift.TBase<TScanRangeLocation, TScanRangeLocation._Fields>, java.io.Serializable, Cloneable, Comparable<TScanRangeLocation> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TScanRangeLocation");

  private static final org.apache.thrift.protocol.TField HOST_IDX_FIELD_DESC = new org.apache.thrift.protocol.TField("host_idx", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField VOLUME_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("volume_id", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField IS_CACHED_FIELD_DESC = new org.apache.thrift.protocol.TField("is_cached", org.apache.thrift.protocol.TType.BOOL, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TScanRangeLocationStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TScanRangeLocationTupleSchemeFactory());
  }

  public int host_idx; // required
  public int volume_id; // optional
  public boolean is_cached; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    HOST_IDX((short)1, "host_idx"),
    VOLUME_ID((short)2, "volume_id"),
    IS_CACHED((short)3, "is_cached");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // HOST_IDX
          return HOST_IDX;
        case 2: // VOLUME_ID
          return VOLUME_ID;
        case 3: // IS_CACHED
          return IS_CACHED;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __HOST_IDX_ISSET_ID = 0;
  private static final int __VOLUME_ID_ISSET_ID = 1;
  private static final int __IS_CACHED_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.VOLUME_ID,_Fields.IS_CACHED};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.HOST_IDX, new org.apache.thrift.meta_data.FieldMetaData("host_idx", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.VOLUME_ID, new org.apache.thrift.meta_data.FieldMetaData("volume_id", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.IS_CACHED, new org.apache.thrift.meta_data.FieldMetaData("is_cached", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TScanRangeLocation.class, metaDataMap);
  }

  public TScanRangeLocation() {
    this.volume_id = -1;

    this.is_cached = false;

  }

  public TScanRangeLocation(
    int host_idx)
  {
    this();
    this.host_idx = host_idx;
    setHost_idxIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TScanRangeLocation(TScanRangeLocation other) {
    __isset_bitfield = other.__isset_bitfield;
    this.host_idx = other.host_idx;
    this.volume_id = other.volume_id;
    this.is_cached = other.is_cached;
  }

  public TScanRangeLocation deepCopy() {
    return new TScanRangeLocation(this);
  }

  @Override
  public void clear() {
    setHost_idxIsSet(false);
    this.host_idx = 0;
    this.volume_id = -1;

    this.is_cached = false;

  }

  public int getHost_idx() {
    return this.host_idx;
  }

  public TScanRangeLocation setHost_idx(int host_idx) {
    this.host_idx = host_idx;
    setHost_idxIsSet(true);
    return this;
  }

  public void unsetHost_idx() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __HOST_IDX_ISSET_ID);
  }

  /** Returns true if field host_idx is set (has been assigned a value) and false otherwise */
  public boolean isSetHost_idx() {
    return EncodingUtils.testBit(__isset_bitfield, __HOST_IDX_ISSET_ID);
  }

  public void setHost_idxIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __HOST_IDX_ISSET_ID, value);
  }

  public int getVolume_id() {
    return this.volume_id;
  }

  public TScanRangeLocation setVolume_id(int volume_id) {
    this.volume_id = volume_id;
    setVolume_idIsSet(true);
    return this;
  }

  public void unsetVolume_id() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __VOLUME_ID_ISSET_ID);
  }

  /** Returns true if field volume_id is set (has been assigned a value) and false otherwise */
  public boolean isSetVolume_id() {
    return EncodingUtils.testBit(__isset_bitfield, __VOLUME_ID_ISSET_ID);
  }

  public void setVolume_idIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __VOLUME_ID_ISSET_ID, value);
  }

  public boolean isIs_cached() {
    return this.is_cached;
  }

  public TScanRangeLocation setIs_cached(boolean is_cached) {
    this.is_cached = is_cached;
    setIs_cachedIsSet(true);
    return this;
  }

  public void unsetIs_cached() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __IS_CACHED_ISSET_ID);
  }

  /** Returns true if field is_cached is set (has been assigned a value) and false otherwise */
  public boolean isSetIs_cached() {
    return EncodingUtils.testBit(__isset_bitfield, __IS_CACHED_ISSET_ID);
  }

  public void setIs_cachedIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __IS_CACHED_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case HOST_IDX:
      if (value == null) {
        unsetHost_idx();
      } else {
        setHost_idx((Integer)value);
      }
      break;

    case VOLUME_ID:
      if (value == null) {
        unsetVolume_id();
      } else {
        setVolume_id((Integer)value);
      }
      break;

    case IS_CACHED:
      if (value == null) {
        unsetIs_cached();
      } else {
        setIs_cached((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case HOST_IDX:
      return getHost_idx();

    case VOLUME_ID:
      return getVolume_id();

    case IS_CACHED:
      return isIs_cached();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case HOST_IDX:
      return isSetHost_idx();
    case VOLUME_ID:
      return isSetVolume_id();
    case IS_CACHED:
      return isSetIs_cached();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TScanRangeLocation)
      return this.equals((TScanRangeLocation)that);
    return false;
  }

  public boolean equals(TScanRangeLocation that) {
    if (that == null)
      return false;

    boolean this_present_host_idx = true;
    boolean that_present_host_idx = true;
    if (this_present_host_idx || that_present_host_idx) {
      if (!(this_present_host_idx && that_present_host_idx))
        return false;
      if (this.host_idx != that.host_idx)
        return false;
    }

    boolean this_present_volume_id = true && this.isSetVolume_id();
    boolean that_present_volume_id = true && that.isSetVolume_id();
    if (this_present_volume_id || that_present_volume_id) {
      if (!(this_present_volume_id && that_present_volume_id))
        return false;
      if (this.volume_id != that.volume_id)
        return false;
    }

    boolean this_present_is_cached = true && this.isSetIs_cached();
    boolean that_present_is_cached = true && that.isSetIs_cached();
    if (this_present_is_cached || that_present_is_cached) {
      if (!(this_present_is_cached && that_present_is_cached))
        return false;
      if (this.is_cached != that.is_cached)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_host_idx = true;
    list.add(present_host_idx);
    if (present_host_idx)
      list.add(host_idx);

    boolean present_volume_id = true && (isSetVolume_id());
    list.add(present_volume_id);
    if (present_volume_id)
      list.add(volume_id);

    boolean present_is_cached = true && (isSetIs_cached());
    list.add(present_is_cached);
    if (present_is_cached)
      list.add(is_cached);

    return list.hashCode();
  }

  @Override
  public int compareTo(TScanRangeLocation other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetHost_idx()).compareTo(other.isSetHost_idx());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHost_idx()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.host_idx, other.host_idx);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetVolume_id()).compareTo(other.isSetVolume_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVolume_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.volume_id, other.volume_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIs_cached()).compareTo(other.isSetIs_cached());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIs_cached()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.is_cached, other.is_cached);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TScanRangeLocation(");
    boolean first = true;

    sb.append("host_idx:");
    sb.append(this.host_idx);
    first = false;
    if (isSetVolume_id()) {
      if (!first) sb.append(", ");
      sb.append("volume_id:");
      sb.append(this.volume_id);
      first = false;
    }
    if (isSetIs_cached()) {
      if (!first) sb.append(", ");
      sb.append("is_cached:");
      sb.append(this.is_cached);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'host_idx' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TScanRangeLocationStandardSchemeFactory implements SchemeFactory {
    public TScanRangeLocationStandardScheme getScheme() {
      return new TScanRangeLocationStandardScheme();
    }
  }

  private static class TScanRangeLocationStandardScheme extends StandardScheme<TScanRangeLocation> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TScanRangeLocation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // HOST_IDX
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.host_idx = iprot.readI32();
              struct.setHost_idxIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // VOLUME_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.volume_id = iprot.readI32();
              struct.setVolume_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // IS_CACHED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.is_cached = iprot.readBool();
              struct.setIs_cachedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetHost_idx()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'host_idx' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TScanRangeLocation struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(HOST_IDX_FIELD_DESC);
      oprot.writeI32(struct.host_idx);
      oprot.writeFieldEnd();
      if (struct.isSetVolume_id()) {
        oprot.writeFieldBegin(VOLUME_ID_FIELD_DESC);
        oprot.writeI32(struct.volume_id);
        oprot.writeFieldEnd();
      }
      if (struct.isSetIs_cached()) {
        oprot.writeFieldBegin(IS_CACHED_FIELD_DESC);
        oprot.writeBool(struct.is_cached);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TScanRangeLocationTupleSchemeFactory implements SchemeFactory {
    public TScanRangeLocationTupleScheme getScheme() {
      return new TScanRangeLocationTupleScheme();
    }
  }

  private static class TScanRangeLocationTupleScheme extends TupleScheme<TScanRangeLocation> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TScanRangeLocation struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.host_idx);
      BitSet optionals = new BitSet();
      if (struct.isSetVolume_id()) {
        optionals.set(0);
      }
      if (struct.isSetIs_cached()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetVolume_id()) {
        oprot.writeI32(struct.volume_id);
      }
      if (struct.isSetIs_cached()) {
        oprot.writeBool(struct.is_cached);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TScanRangeLocation struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.host_idx = iprot.readI32();
      struct.setHost_idxIsSet(true);
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.volume_id = iprot.readI32();
        struct.setVolume_idIsSet(true);
      }
      if (incoming.get(1)) {
        struct.is_cached = iprot.readBool();
        struct.setIs_cachedIsSet(true);
      }
    }
  }

}

