/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.impala.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)")
public class TSummaryStatsCounter implements org.apache.thrift.TBase<TSummaryStatsCounter, TSummaryStatsCounter._Fields>, java.io.Serializable, Cloneable, Comparable<TSummaryStatsCounter> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TSummaryStatsCounter");

  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField UNIT_FIELD_DESC = new org.apache.thrift.protocol.TField("unit", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField SUM_FIELD_DESC = new org.apache.thrift.protocol.TField("sum", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField TOTAL_NUM_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("total_num_values", org.apache.thrift.protocol.TType.I64, (short)4);
  private static final org.apache.thrift.protocol.TField MIN_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("min_value", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField MAX_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("max_value", org.apache.thrift.protocol.TType.I64, (short)6);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TSummaryStatsCounterStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TSummaryStatsCounterTupleSchemeFactory());
  }

  private String name; // required
  private org.apache.impala.thrift.TUnit unit; // required
  private long sum; // required
  private long total_num_values; // required
  private long min_value; // required
  private long max_value; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NAME((short)1, "name"),
    /**
     * 
     * @see org.apache.impala.thrift.TUnit
     */
    UNIT((short)2, "unit"),
    SUM((short)3, "sum"),
    TOTAL_NUM_VALUES((short)4, "total_num_values"),
    MIN_VALUE((short)5, "min_value"),
    MAX_VALUE((short)6, "max_value");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NAME
          return NAME;
        case 2: // UNIT
          return UNIT;
        case 3: // SUM
          return SUM;
        case 4: // TOTAL_NUM_VALUES
          return TOTAL_NUM_VALUES;
        case 5: // MIN_VALUE
          return MIN_VALUE;
        case 6: // MAX_VALUE
          return MAX_VALUE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SUM_ISSET_ID = 0;
  private static final int __TOTAL_NUM_VALUES_ISSET_ID = 1;
  private static final int __MIN_VALUE_ISSET_ID = 2;
  private static final int __MAX_VALUE_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.UNIT, new org.apache.thrift.meta_data.FieldMetaData("unit", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, org.apache.impala.thrift.TUnit.class)));
    tmpMap.put(_Fields.SUM, new org.apache.thrift.meta_data.FieldMetaData("sum", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.TOTAL_NUM_VALUES, new org.apache.thrift.meta_data.FieldMetaData("total_num_values", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.MIN_VALUE, new org.apache.thrift.meta_data.FieldMetaData("min_value", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.MAX_VALUE, new org.apache.thrift.meta_data.FieldMetaData("max_value", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TSummaryStatsCounter.class, metaDataMap);
  }

  public TSummaryStatsCounter() {
  }

  public TSummaryStatsCounter(
    String name,
    org.apache.impala.thrift.TUnit unit,
    long sum,
    long total_num_values,
    long min_value,
    long max_value)
  {
    this();
    this.name = name;
    this.unit = unit;
    this.sum = sum;
    setSumIsSet(true);
    this.total_num_values = total_num_values;
    setTotal_num_valuesIsSet(true);
    this.min_value = min_value;
    setMin_valueIsSet(true);
    this.max_value = max_value;
    setMax_valueIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TSummaryStatsCounter(TSummaryStatsCounter other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetName()) {
      this.name = other.name;
    }
    if (other.isSetUnit()) {
      this.unit = other.unit;
    }
    this.sum = other.sum;
    this.total_num_values = other.total_num_values;
    this.min_value = other.min_value;
    this.max_value = other.max_value;
  }

  public TSummaryStatsCounter deepCopy() {
    return new TSummaryStatsCounter(this);
  }

  @Override
  public void clear() {
    this.name = null;
    this.unit = null;
    setSumIsSet(false);
    this.sum = 0;
    setTotal_num_valuesIsSet(false);
    this.total_num_values = 0;
    setMin_valueIsSet(false);
    this.min_value = 0;
    setMax_valueIsSet(false);
    this.max_value = 0;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  /**
   * 
   * @see org.apache.impala.thrift.TUnit
   */
  public org.apache.impala.thrift.TUnit getUnit() {
    return this.unit;
  }

  /**
   * 
   * @see org.apache.impala.thrift.TUnit
   */
  public void setUnit(org.apache.impala.thrift.TUnit unit) {
    this.unit = unit;
  }

  public void unsetUnit() {
    this.unit = null;
  }

  /** Returns true if field unit is set (has been assigned a value) and false otherwise */
  public boolean isSetUnit() {
    return this.unit != null;
  }

  public void setUnitIsSet(boolean value) {
    if (!value) {
      this.unit = null;
    }
  }

  public long getSum() {
    return this.sum;
  }

  public void setSum(long sum) {
    this.sum = sum;
    setSumIsSet(true);
  }

  public void unsetSum() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SUM_ISSET_ID);
  }

  /** Returns true if field sum is set (has been assigned a value) and false otherwise */
  public boolean isSetSum() {
    return EncodingUtils.testBit(__isset_bitfield, __SUM_ISSET_ID);
  }

  public void setSumIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SUM_ISSET_ID, value);
  }

  public long getTotal_num_values() {
    return this.total_num_values;
  }

  public void setTotal_num_values(long total_num_values) {
    this.total_num_values = total_num_values;
    setTotal_num_valuesIsSet(true);
  }

  public void unsetTotal_num_values() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TOTAL_NUM_VALUES_ISSET_ID);
  }

  /** Returns true if field total_num_values is set (has been assigned a value) and false otherwise */
  public boolean isSetTotal_num_values() {
    return EncodingUtils.testBit(__isset_bitfield, __TOTAL_NUM_VALUES_ISSET_ID);
  }

  public void setTotal_num_valuesIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TOTAL_NUM_VALUES_ISSET_ID, value);
  }

  public long getMin_value() {
    return this.min_value;
  }

  public void setMin_value(long min_value) {
    this.min_value = min_value;
    setMin_valueIsSet(true);
  }

  public void unsetMin_value() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __MIN_VALUE_ISSET_ID);
  }

  /** Returns true if field min_value is set (has been assigned a value) and false otherwise */
  public boolean isSetMin_value() {
    return EncodingUtils.testBit(__isset_bitfield, __MIN_VALUE_ISSET_ID);
  }

  public void setMin_valueIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __MIN_VALUE_ISSET_ID, value);
  }

  public long getMax_value() {
    return this.max_value;
  }

  public void setMax_value(long max_value) {
    this.max_value = max_value;
    setMax_valueIsSet(true);
  }

  public void unsetMax_value() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __MAX_VALUE_ISSET_ID);
  }

  /** Returns true if field max_value is set (has been assigned a value) and false otherwise */
  public boolean isSetMax_value() {
    return EncodingUtils.testBit(__isset_bitfield, __MAX_VALUE_ISSET_ID);
  }

  public void setMax_valueIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __MAX_VALUE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((String)value);
      }
      break;

    case UNIT:
      if (value == null) {
        unsetUnit();
      } else {
        setUnit((org.apache.impala.thrift.TUnit)value);
      }
      break;

    case SUM:
      if (value == null) {
        unsetSum();
      } else {
        setSum((Long)value);
      }
      break;

    case TOTAL_NUM_VALUES:
      if (value == null) {
        unsetTotal_num_values();
      } else {
        setTotal_num_values((Long)value);
      }
      break;

    case MIN_VALUE:
      if (value == null) {
        unsetMin_value();
      } else {
        setMin_value((Long)value);
      }
      break;

    case MAX_VALUE:
      if (value == null) {
        unsetMax_value();
      } else {
        setMax_value((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case NAME:
      return getName();

    case UNIT:
      return getUnit();

    case SUM:
      return getSum();

    case TOTAL_NUM_VALUES:
      return getTotal_num_values();

    case MIN_VALUE:
      return getMin_value();

    case MAX_VALUE:
      return getMax_value();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case NAME:
      return isSetName();
    case UNIT:
      return isSetUnit();
    case SUM:
      return isSetSum();
    case TOTAL_NUM_VALUES:
      return isSetTotal_num_values();
    case MIN_VALUE:
      return isSetMin_value();
    case MAX_VALUE:
      return isSetMax_value();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TSummaryStatsCounter)
      return this.equals((TSummaryStatsCounter)that);
    return false;
  }

  public boolean equals(TSummaryStatsCounter that) {
    if (that == null)
      return false;

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_unit = true && this.isSetUnit();
    boolean that_present_unit = true && that.isSetUnit();
    if (this_present_unit || that_present_unit) {
      if (!(this_present_unit && that_present_unit))
        return false;
      if (!this.unit.equals(that.unit))
        return false;
    }

    boolean this_present_sum = true;
    boolean that_present_sum = true;
    if (this_present_sum || that_present_sum) {
      if (!(this_present_sum && that_present_sum))
        return false;
      if (this.sum != that.sum)
        return false;
    }

    boolean this_present_total_num_values = true;
    boolean that_present_total_num_values = true;
    if (this_present_total_num_values || that_present_total_num_values) {
      if (!(this_present_total_num_values && that_present_total_num_values))
        return false;
      if (this.total_num_values != that.total_num_values)
        return false;
    }

    boolean this_present_min_value = true;
    boolean that_present_min_value = true;
    if (this_present_min_value || that_present_min_value) {
      if (!(this_present_min_value && that_present_min_value))
        return false;
      if (this.min_value != that.min_value)
        return false;
    }

    boolean this_present_max_value = true;
    boolean that_present_max_value = true;
    if (this_present_max_value || that_present_max_value) {
      if (!(this_present_max_value && that_present_max_value))
        return false;
      if (this.max_value != that.max_value)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_name = true && (isSetName());
    list.add(present_name);
    if (present_name)
      list.add(name);

    boolean present_unit = true && (isSetUnit());
    list.add(present_unit);
    if (present_unit)
      list.add(unit.getValue());

    boolean present_sum = true;
    list.add(present_sum);
    if (present_sum)
      list.add(sum);

    boolean present_total_num_values = true;
    list.add(present_total_num_values);
    if (present_total_num_values)
      list.add(total_num_values);

    boolean present_min_value = true;
    list.add(present_min_value);
    if (present_min_value)
      list.add(min_value);

    boolean present_max_value = true;
    list.add(present_max_value);
    if (present_max_value)
      list.add(max_value);

    return list.hashCode();
  }

  @Override
  public int compareTo(TSummaryStatsCounter other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUnit()).compareTo(other.isSetUnit());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUnit()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.unit, other.unit);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSum()).compareTo(other.isSetSum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sum, other.sum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTotal_num_values()).compareTo(other.isSetTotal_num_values());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTotal_num_values()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.total_num_values, other.total_num_values);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMin_value()).compareTo(other.isSetMin_value());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMin_value()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.min_value, other.min_value);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMax_value()).compareTo(other.isSetMax_value());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMax_value()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.max_value, other.max_value);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TSummaryStatsCounter(");
    boolean first = true;

    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("unit:");
    if (this.unit == null) {
      sb.append("null");
    } else {
      sb.append(this.unit);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("sum:");
    sb.append(this.sum);
    first = false;
    if (!first) sb.append(", ");
    sb.append("total_num_values:");
    sb.append(this.total_num_values);
    first = false;
    if (!first) sb.append(", ");
    sb.append("min_value:");
    sb.append(this.min_value);
    first = false;
    if (!first) sb.append(", ");
    sb.append("max_value:");
    sb.append(this.max_value);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!isSetName()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'name' is unset! Struct:" + toString());
    }

    if (!isSetUnit()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'unit' is unset! Struct:" + toString());
    }

    if (!isSetSum()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'sum' is unset! Struct:" + toString());
    }

    if (!isSetTotal_num_values()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'total_num_values' is unset! Struct:" + toString());
    }

    if (!isSetMin_value()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'min_value' is unset! Struct:" + toString());
    }

    if (!isSetMax_value()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'max_value' is unset! Struct:" + toString());
    }

    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TSummaryStatsCounterStandardSchemeFactory implements SchemeFactory {
    public TSummaryStatsCounterStandardScheme getScheme() {
      return new TSummaryStatsCounterStandardScheme();
    }
  }

  private static class TSummaryStatsCounterStandardScheme extends StandardScheme<TSummaryStatsCounter> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TSummaryStatsCounter struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // UNIT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.unit = org.apache.impala.thrift.TUnit.findByValue(iprot.readI32());
              struct.setUnitIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SUM
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.sum = iprot.readI64();
              struct.setSumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TOTAL_NUM_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.total_num_values = iprot.readI64();
              struct.setTotal_num_valuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // MIN_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.min_value = iprot.readI64();
              struct.setMin_valueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // MAX_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.max_value = iprot.readI64();
              struct.setMax_valueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TSummaryStatsCounter struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      if (struct.unit != null) {
        oprot.writeFieldBegin(UNIT_FIELD_DESC);
        oprot.writeI32(struct.unit.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SUM_FIELD_DESC);
      oprot.writeI64(struct.sum);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TOTAL_NUM_VALUES_FIELD_DESC);
      oprot.writeI64(struct.total_num_values);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(MIN_VALUE_FIELD_DESC);
      oprot.writeI64(struct.min_value);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(MAX_VALUE_FIELD_DESC);
      oprot.writeI64(struct.max_value);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TSummaryStatsCounterTupleSchemeFactory implements SchemeFactory {
    public TSummaryStatsCounterTupleScheme getScheme() {
      return new TSummaryStatsCounterTupleScheme();
    }
  }

  private static class TSummaryStatsCounterTupleScheme extends TupleScheme<TSummaryStatsCounter> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TSummaryStatsCounter struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.name);
      oprot.writeI32(struct.unit.getValue());
      oprot.writeI64(struct.sum);
      oprot.writeI64(struct.total_num_values);
      oprot.writeI64(struct.min_value);
      oprot.writeI64(struct.max_value);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TSummaryStatsCounter struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.name = iprot.readString();
      struct.setNameIsSet(true);
      struct.unit = org.apache.impala.thrift.TUnit.findByValue(iprot.readI32());
      struct.setUnitIsSet(true);
      struct.sum = iprot.readI64();
      struct.setSumIsSet(true);
      struct.total_num_values = iprot.readI64();
      struct.setTotal_num_valuesIsSet(true);
      struct.min_value = iprot.readI64();
      struct.setMin_valueIsSet(true);
      struct.max_value = iprot.readI64();
      struct.setMax_valueIsSet(true);
    }
  }

}

